FROM node:14.15.1 as build

WORKDIR /usr/local/app

COPY . /usr/local/app/

RUN yarn install

RUN yarn ng build

FROM nginx:latest

COPY --from=build /usr/local/app/dist/ /usr/share/nginx/html
COPY --from=build /usr/local/app/default.conf.template /etc/nginx/conf.d
COPY --from=build /usr/local/app/docker_entrypoint.sh /docker-entrypoint.d

RUN chmod +x /docker-entrypoint.d/docker_entrypoint.sh
