name: CI/CD

on: [push, pull_request]

jobs:
  test:
    name: Test
    environment: heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version-file: .nvmrc
          cache-dependency-path: yarn.lock
          
      - name: Install Dependencies
        run: yarn
        
      - name: Run Tests
        run: yarn woop
        
  deploy:
    name: Deployment
    needs: [test]
    if: github.ref == 'refs/heads/main'
    environment: heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push --arg ENV=production,SHA=$GITHUB_SHA -a jbanass-site --recursive

      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web -a jbanass-site
